### ISSUE TITLE
Not able to deploy jboss in azure vm getting access denied error

### ISSUE THREAD

**Issue by prabaharanit** [microsoft/redhat-mw-cloud-quickstart#12]
getting below error while running standalone eap 7 script 

https://github.com/microsoft/redhat-mw-cloud-quickstart/tree/master/jboss-eap-standalone-rhel7

{'code':'DeploymentFailed','message':'At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.','details':[{'code':'Conflict','message':'{\\r\\n \\'status\\': \\'Failed\\',\\r\\n \\'error\\': {\\r\\n \\'code\\': \\'ResourceDeploymentFailure\\',\\r\\n \\'message\\': \\'The resource operation completed with terminal provisioning state 'Failed'.\\',\\r\\n \\'details\\': [\\r\\n {\\r\\n \\'code\\': \\'VMExtensionProvisioningError\\',\\r\\n \\'message\\': \\'VM has reported a failure when processing extension 'newuserscript'. Error message: \\\\\\'Enable failed: failed to execute command: command terminated with exit status=1\\\\n[stdout]\\\\nLoaded plugins: langpacks, product-id\\\\n\\\\n[stderr]\\\\nFailed to execute operation: Access denied\\\\neap-setup-redhat.sh: line 37: /etc/opt/rh/eap7/wildfly/eap7-standalone.conf: No such file or directory\\\\neap-setup-redhat.sh: line 38: /etc/opt/rh/eap7/wildfly/eap7-standalone.conf: No such file or directory\\\\nmv: cannot move ‘/home/vmadmin_2019/dukes/target/dukes.war’ to ‘/opt/rh/eap7/root/usr/share/wildfly/standalone/deployments/dukes.war’: No such file or directory\\\\neap-setup-redhat.sh: line 47: /opt/rh/eap7/root/usr/share/wildfly/standalone/deployments/dukes.war.dodeploy: No such file or directory\\\\neap-setup-redhat.sh: line 50: /opt/rh/eap7/root/usr/share/wildfly/bin/add-user.sh: No such file or directory\\\\nFailed to restart eap7-standalone.service: Unit eap7-standalone.service failed to load: No such file or directory.\\\\nchown: invalid user: ‘vmadmin_2019.jboss’\\\\nchown: invalid user: ‘vmadmin_2019.jboss’\\\\nchown: invalid user: ‘vmadmin_2019.tomcat’\\\\nchown: invalid user: ‘vmadmin_2019.jboss’\\\\nchown: invalid user: ‘vmadmin_2019.jboss’\\\\n\\\\\\'.\\'\\r\\n }\\r\\n ]\\r\\n }\\r\\n}'}]}

**Comment by gbowerman** [comment]
@prabaharanit the template is deploying successfully for me. Can you try deploying with a user name containing no punctuation, and making sure you're using a valid Red Hat account where required, and see if the result is any different?

**Comment by prabaharanit** [comment]
@gbowerman , issue was with wrong pool id, which got fixed after providing poolid which was associated with the jboss from subscription manager.
